global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'oneleaf-benchmark'
    static_configs:
      - targets: ['oneleaf-bench:9090']
        labels:
          engine: 'oneleaf'

  - job_name: 'pebble-benchmark'
    static_configs:
      - targets: ['pebble-bench:9090']
        labels:
          engine: 'pebble'
